language: php
php:
  - 5.6
  - 7.0
  - 7.1
before_script:
  - pear install Console_CommandLine
  - php composer.phar self-update
  - php composer.phar install --dev
  - phpenv rehash
script: phpunit --configuration ./tests/phpunit.xml
