language: php
php:
  - 7.3
  - 7.4
  - 8.0.1
before_script:
  - php composer.phar self-update
  - php composer.phar install
  - phpenv rehash
script: ./vendor/phpunit/phpunit/phpunit --configuration ./tests/phpunit.xml
