language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
before_script:
  - pear install Console_CommandLine
  - php composer.phar self-update
  - php composer.phar install --dev
  - phpenv rehash
script: phpunit --configuration ./tests/phpunit.xml
